name: baseline
num_epochs: 2000

data:
  dataset: normal
  data_dir: ${env.data_dir}
  resolution: ${method.model.resolution}
  train_ratio: 0.95
  batch_size: 64

model:
  _target_: modules.baseline.pl_model.BaselineModule
  resolution: 256
