name: lightweight
num_epochs: 2000

data:
  dataset:
    _target_: data_modules.normal.NormalDataset
  data_dir: ${env.data_dir}
  resolution: ${method.model.resolution}
  train_ratio: 0.95
  batch_size: 64

model:
  _target_: modules.lightweight.pl_model.LightweightModule
  resolution: 256
